const n = {
  page: 1,
  results: [
    {
      adult: false,
      backdrop_path: null,
      genre_ids: [99, 36],
      id: 229696,
      original_language: 'pt',
      original_title: 'Jango',
      overview: 'The story of João "Jango" Goulart, the Brazilian left-wing president deposed by the military.',
      popularity: 1.032,
      poster_path: '/rttnXQ6FFhl0KzwkXCfsFq4etH8.jpg',
      release_date: '1984-10-23',
      title: 'Jango',
      video: false,
      vote_average: 6.3,
      vote_count: 5,
    },
    {
      adult: false,
      backdrop_path: '/p1wNju5JMO2n2M1iVLkJerAi7LF.jpg',
      genre_ids: [37],
      id: 535366,
      original_language: 'pt',
      original_title: 'Jango',
      overview: '',
      popularity: 0.854,
      poster_path: '/rufbSH7JpvQBejihkiAP9uvrnSB.jpg',
      release_date: '2017-10-19',
      title: 'Jango',
      video: false,
      vote_average: 0,
      vote_count: 0,
    },
    {
      adult: false,
      backdrop_path: null,
      genre_ids: [12, 35],
      id: 452418,
      original_language: 'sv',
      original_title: 'Jango on Tour',
      overview: 'A road movie about the aspiring film director Mårten and his friends.',
      popularity: 0.6,
      poster_path: '/ep4guAd0M4MtbESyXxWJZrcRWc8.jpg',
      release_date: '2011-11-23',
      title: 'Jango on Tour',
      video: false,
      vote_average: 0,
      vote_count: 0,
    },
    {
      adult: false,
      backdrop_path: null,
      genre_ids: [28, 37],
      id: 709225,
      original_language: 'pt',
      original_title: 'Jango Bravo',
      overview: '',
      popularity: 0.6,
      poster_path: '/gkvBr7jkWiZ0rj1DzNlwSqv4xgi.jpg',
      release_date: '2006-01-01',
      title: 'Jango Bravo',
      video: false,
      vote_average: 0,
      vote_count: 0,
    },
    {
      adult: false,
      backdrop_path: null,
      genre_ids: [99],
      id: 240852,
      original_language: 'pt',
      original_title: 'Dossiê Jango',
      overview:
        'João Goulart (known as Jango) had been democratically elected president of Brazil, but was expelled from office after the coup of April 1, 1964. After that, Jango lived in exile in Argentina, where he died in 1976. The circumstances of his death in the neighboring country were not well explained today. His body was buried immediately after his death, raising the suspicions of premeditated murder. This documentary brings the issue back to the fore and tries to publicly clarify some obscure facts of the history of Brazil.',
      popularity: 0.6,
      poster_path: null,
      release_date: '2013-07-05',
      title: 'Dossiê Jango',
      video: false,
      vote_average: 7,
      vote_count: 3,
    },
    {
      adult: false,
      backdrop_path: null,
      genre_ids: [99],
      id: 513004,
      original_language: 'pt',
      original_title: 'Jango em 3 Atos',
      overview:
        'The political and domestic life of João Goulart, brazilian president victim of a civil-militar coup in 1964.',
      popularity: 0.6,
      poster_path: '/dZUp3D32CLPhjVoN4U51ELeoZNh.jpg',
      release_date: '2008-10-15',
      title: 'Jango em 3 Atos',
      video: false,
      vote_average: 0,
      vote_count: 0,
    },
    {
      adult: false,
      backdrop_path: null,
      genre_ids: [10402, 16, 14, 35],
      id: 464154,
      original_language: 'ja',
      original_title: 'ONE PIECE ジャンゴのダンスカーニバル',
      overview:
        "The Straw Hat Pirates visit Mirrorball Island. Where a big dance carnival is being held. Jango the Hypnotist was there too, to show off his dance moves. Only when he was found by a group of Marines who were about to arrest him. But ended up chasing him throughout the island. Our heroes got involved when one of the Marines recognized Luffy from the wanted poster. And they end up getting chased as well. Soon Jango steals the spotlight of the dance carnival and uses his hypnosis on everyone on the island. And soon everyone including Jango, The StrawHat Pirates, and the marines are all dancing like there's no tomorrow.",
      popularity: 8.072,
      poster_path: '/zCOhyBSx1WdcGfDDqvBtCsmBZwd.jpg',
      release_date: '2001-03-03',
      title: "One Piece: Jango's Dance Carnival",
      video: false,
      vote_average: 8.3,
      vote_count: 9,
    },
  ],
  total_pages: 1,
  total_results: 7,
};

// n.results.map(movie => console.log(movie.title))

const movies_res = fetch(
  'https://api.themoviedb.org/3/search/movie/?api_key=4a2f017c8cdb38c57478d603057ad10e&query=return'
).then((response) => console.log(response));

({ list_arr, toggle_status, remove_todo });
